name: Issue Triage
on:
  issues:
    types:
      - opened
jobs:
  issue_triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pierotofy/issuewhiz@main
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          openAI: ${{ secrets.OPENAI_TOKEN }}
          filter: |
            - "#"
          variables: |
            - A: "A question about using a software or seeking guidance on doing something?"
            - B: "Reporting an issue or a software bug?"
            - C: "Describes an issue with processing a set of images or a particular dataset"
            - D: "Contains a link to a dataset or images?"
            - E: "Contains a suggestion for an improvement or a feature request?"
            - F: "Describes an issue related to compiling or building source code?"
          logic: |
            - "A and (not B) and (not C)": [comment: "Please use forum", close: true, stop: true]
            - "B and (not C) and (not E)": [label: bug, stop: true]
            - "C and (not D) and (not F)": [comment: "dataset missing", close: true, stop: true]
            - "C and D": [label: "possible bug", stop: true]
            - "E and (not B) and (not C)": [label: enhancement]
          signature: "p.s. I'm just an automated script, not a human being."