name: Issue Triage
on:
  issues:
    types:
      - opened
jobs:
  issue_triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pierotofy/issuewhiz@main
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          openAI: ${{ secrets.OPENAI_TOKEN }}
          filter: |
            - "#"
          variables: |
            - A: "A question about using a software?"
            - B: "Reporting an issue or a bug?"
            - C: "An issue with processing?"
            - D: "Contains a link to a dataset or images?"
          logic: |
            - "A and (not B) and (not C)": [comment: "Please use forum", close: true, stop: true]
            - "B and (not C)": [label: bug, stop: true]
            - "C and (not D)": [comment: "dataset missing", close: true, stop: true]
          signature: "p.s. I'm just an automated script, not a human being."