name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  triage_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pierotofy/issuewhiz@main
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          openAI: ${{ secrets.OPENAI_TOKEN }}
          variables:
            - A: "Is this text about asking a question on using a software?"
            - B: "Is this text about reporting an issue or a bug?"
            - C: "Is this text about an issue with processing?"
          logic:
            - "A & NOT(B)": [abc: "Question", close: True, stop: True]
            - "C": [abc: "Processing", qwe: asd]
