name: Test

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set swap
      uses: pierotofy/set-swap-space@master
      with: 
        swap-size-gb: 6
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
