
name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  triage_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pierotofy/issuewhiz@main
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          openAI: ${{ secrets.OPENAI_TOKEN }}
          filter:
            - "#": ""
          variables:
            - A: Asking a question on using a software?
            - B: Reporting an issue or a bug?
            - C: An issue with processing?
          logic:
            - - expr: A & NOT(B)
              - comment: Question
              - close: true
              - stop: true
            - - expr: C
              - comment: Processing
              - label: enhancement
