name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  scan_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pierotofy/issuewhiz
        with:
            ghToken: {{ secrets.GITHUB_TOKEN }}
